# Generated by Django 4.0.2 on 2022-02-02 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 22, 30, 48, 697409)),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
